import React from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";
// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Ecovista | Learn With Sumit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
